### PR TITLE
Improve support for JSX

### LINKED ISSUE #766: React JSX syntax breaks highlighting
See #494 

This [example][jsb] clearly shows the JSX tags breaking highlighting:

screen shot 2015-02-26 at 6 18 36 pm

XML sections are [expected to end with `">;"`][1], whereas this XML is parenthesized. Changing the pattern to `/>[\)\]]?;/` would fix this.

See also https://github.com/Reviewable/Reviewable/issues/47

[jsb]: http://jsbin.com/selosizihi/1/edit?html,output
[1]: https://github.com/isagalaev/highlight.js/blob/master/src/languages/javascript.js#L47

### PR DESCRIPTION
**Pull request by danvk**
Fixes #766 

Also adds a few JavaScript markup tests -- one using [React JSX syntax][1], one using the JavaScript example from the highlight.js home page.

[1]: http://facebook.github.io/react/docs/jsx-in-depth.html

### CODE REVIEW

**Comment by isagalaev** [comment]
Coming from the description in #766, I was about to ask you to also add optional whitespace after `>` but you've been reading my mind apparently :-). Thanks!

**Comment by isagalaev** [comment]
Oh and a very special thank you for adding tests, too!

**Comment by danvk** [comment]
Thanks for merging! Any guesses when the next release of highlight.js will go out?

**Comment by isagalaev** [comment]
We've got [10 open issues][1] targeted for the next release and, judging by past empirical evidence, we might sort it out in two coming weeks.

[1]: https://github.com/isagalaev/highlight.js/milestones/8.5

**Comment by knowbody** [comment]
why can't we use the same rules [babel-sublime](https://github.com/babel/babel-sublime) is using? it's doing a pretty good job with JSX

**Comment by Strate** [comment]
Could you please improve support of typescript with embedded jsx? (it called tsx)

**Pull request merged**
