### PR TITLE
Fix annotation collections for clojure

### PR DESCRIPTION
**Pull request by maacl**
Current HINT_COL exits at first }.

### CODE REVIEW

**Comment by isagalaev** [comment]
Could you also write a short test for it? Here's the guideline: http://highlightjs.readthedocs.io/en/latest/building-testing.html#testing-markup

**Comment by maacl** [comment]
Sure, done.

**Comment by isagalaev** [comment]
Merged. Thank you for the contribution!

**Comment by isagalaev** [comment]
Forgot one more thing! Could you also add yourself to AUTHORS.en.txt and as `Contributors: Your Name <email@server>` to clojure.js headers. Unless you don't want to be mentioned, of course…

**Pull request merged**
