### PR TITLE
Improve coding style

### PR DESCRIPTION
**Pull request by marcobiedermann**
* sort properties alphabetically
* add space after color
* indent using two spaces
* shorten hex color notation
* use hex notation instead of keyword
* use longhand instead of shorthand
* remove trailing whitespace
* write color hex notation in lowercase

### CODE REVIEW

**Comment by isagalaev** [comment]
Frankly, I don't see how it improves anything. It's a purely stylistic change from one preference to another.

**Comment by derhuerst** [comment]
Note that some of it aligns the code to [what's stated in the `.editorconfig`](https://github.com/isagalaev/highlight.js/blob/4c96012/.editorconfig).

**Comment by marcobiedermann** [comment]
@isagalaev It helps to ensure a better coding style, which is easier to maintain and to extend.
Also it helps saving a few bytes when using GZIP compression.

**Comment by derhuerst** [comment]
> @isagalaev It helps to ensure a better coding style, which is easier to maintain and to extend.

IMHO that's a matter of taste.

**Comment by Sannis** [comment]
I have no objections to accept or decline this, hope this will not become code-style war :-)

**Comment by isagalaev** [comment]
Sorry for taking so long to answer, I've been away from the project.

Ultimately, we don't want this change as it doesn't bring anything substantial. `#f0f` is not easier to maintain than `#ff00ff`, neither `#6a8759` vs `#6A8759`, nor `background-color` vs `background`. We simply don't have any tooling that might depend on it.

I appreciate the effort, though.

**Pull request closed without merging**
