### PR TITLE
Augmented Backus–Naur Form

### PR DESCRIPTION
**Pull request by mckibbenta**
ABNF Metalanguage

### CODE REVIEW

**Comment by mckibbenta** [comment]
I just realized that the developer docs say for the contributor to update CHANGES.md themselves. I have not done this. Should I close this request and submit another after updating CHANGES.md?

If so, should I create a new section and everything anticipating the next release number? For example:

* * *

## Version 9.6.0

New languages:

- *ABNF* by [Alex McKibben][]

[Alex McKibben]: https://github.com/mckibbenta

* * *

Seems awkward in a way since every contributor would need to do the same thing. I supposed this is trivial for project maintainers to merge though, so not a big deal. Still, please advise.

**Comment by isagalaev** [comment]
Yes, just add a new section on top `## Version 9.6.0 (not released)`

**Comment by mckibbenta** [comment]
I'm closing this pull request. I'll make the edit to CHANGES.md as discussed and submit another.

**Comment by isagalaev** [comment]
No need to re-create a pull request, as it simply represents you proposal to merge your branch. You could simply commit a new change and push it.

**Comment by mckibbenta** [comment]
I'll remember that, thanks. Been a while since I worked with git. Silly TFS at work.

**Pull request closed without merging**
