### PR TITLE
Added new theme in Atelier-series, Sulphurpool

### PR DESCRIPTION
**Pull request by atelierbram**
Shiny new theme, can be [seen in action for Highlight.js over here](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/demo/highlight-js.html).

### CODE REVIEW

**Comment by Sannis** [comment]
Please go through [Style contributor checklist](http://highlightjs.readthedocs.org/en/latest/style-contribution.html) and make some related changes.

**Comment by Sannis** [comment]
Can you please update this pull requests after #783 merge?

**Comment by atelierbram** [comment]
@Sannis Thanks for the merge. Latest 2 commits reflect the recent changes on the other updated (and merged) _"Atelier-Schemes"_-files.

**Comment by Sannis** [comment]
Thanks!

**Pull request merged**
