### PR TITLE
Add Csound languages

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request adds support for [Csound](https://csound.github.io).

### CODE REVIEW

**Comment by nwhetsell** [comment]
Is there anything I can do to help get this merged?

**Comment by isagalaev** [comment]
No, we're just slow lately. Sorry about that!

**Comment by nwhetsell** [comment]
Just checking again to see if there’s anything I can do to help get this merged.

**Comment by nwhetsell** [comment]
What can I do to help get this merged?

**Comment by nwhetsell** [comment]
I’m closing this since it has gone stale, and also because it’s obsolete for my purposes since [Ace now has a Csound mode](https://github.com/ajaxorg/ace/pull/3398).

**Pull request closed without merging**
