### PR TITLE
Elm language version 0.16 to 0.17 transition

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
This is now all the changes needed to support Elm 0.17. Should I squash the commits, or do you do that on merge?

**Comment by isagalaev** [comment]
@jvoigtlaender thanks! No need to alter commits in any way, we'll look at this PR as soon as someone of the core team find time. Hopefully before next Tuesday when we're going to release the next version.

**Comment by Sannis** [comment]
@jvoigtlaender thanks!

**Comment by jvoigtlaender** [comment]
Thanks for merging! And for highlight.js!

**Comment by isagalaev** [comment]
@jvoigtlaender by the way, if you like the idea of having Elm code in rotation on highlightjs.org, you could trim down the test snippet in test/detect/elm/default.txt to fit into 54 columns and 16 rows of text and I'll be happy to switch it on.

**Pull request merged**
