### PR TITLE
New language: C/AL

### PR DESCRIPTION
**Pull request by kfuglsang**
I added support for the C/AL language used by Microsoft Dynamics NAV C/AL.

### CODE REVIEW

**Comment by forki** [comment]
Very very cool. +1

**Comment by Sannis** [comment]
There is a trivial merge conflict with current master, can you merge it into your branch?

On first look all is ok.

**Comment by kfuglsang** [comment]
Merged with latest upstream

**Comment by forki** [comment]
@kfuglsang  is there a way to use this in fsreveal?

**Comment by kfuglsang** [comment]
@forki Yeah once this PR is resolved.

If the syntax is not autodetected as C/AL you could use `[lang=cal]` to force it.

**Comment by forki** [comment]
even if it get's merged here, there is still reveal.js which needs to be updated, right?

I wonder if we can hack it into fsreveal as a prerelease.

**Comment by kfuglsang** [comment]
Thats true. I could fork reveal.js afterwards to update highlight.js in that. Then we could change fsreveal to use the fork.

**Comment by kfuglsang** [comment]
@Sannis Should be ready to merge.

**Comment by isagalaev** [comment]
BTW, I wouldn't call using this fork a "hack", and it won't be made any more "true" when we merge it with our master branch. So feel free not to wait for us!

**Pull request merged**
