### PR TITLE
WIP: Zephir language highlighting

### PR DESCRIPTION
**Pull request by Sannis**
Pull-request for #736.

### CODE REVIEW

**Comment by Sannis** [comment]
@ovr can you look on this PR to check I don't miss any significant modes or keywords? I used current PHP language definition and https://github.com/phalcon/zephir/blob/master/parser/scanner.re as references.

Also it whould be good if you can suggest some Zephir snippets to be added for tests.

**Comment by ovr** [comment]
@Sannis 

It can helps
https://github.com/phalcon/zephir-lexer
https://github.com/phalcon/zephir-sublime

I will write good\big code snippet ASAP (1, 2 days)

Thank you for your work ;)

**Comment by Sannis** [comment]
Thanks, I'll look on it!

**Comment by ovr** [comment]
Start working on this

```zep

function testBefore(<Test> a, var b = 5, int c = 10) {
	a->method1();

	return b + c;
}

namespace Test;

function testAfter(<Test> a, var b = 5, int c = 10) {
	a->method5();

	return b + c;
}

abstract class CustomClass() {

}

interface TestInterface() {

}

class Test extends CustomClass implements TestInterface
{
	const C1 = null;

	const C2 = false;

	const C3 = true;

	const C4 = 10;

	const C5 = 10.25;

	const C6 = "test";

	//magick consts http://php.net/manual/ru/language.constants.predefined.php
	const className = __CLASS__;

	protected testVar {get, set} = 10;

	protected myArray = [
		"key": [
			"test", "test"
		]
	];

	public function method1(const string phpVersion = PHP_VERSION, var simple = self::C4) -> boolean
	{
		int b, c, sum;

		var a = [1, 2, 3, 4, 4, 5, 6, 7];
		array a = [1, 2, 3, 4, 4, 5, 6, 7];

		char h = 'A';
		string myStr = "example string";

		for ch in str {
			//built-in method toInt
			sum += ch->toInt();
		}

		for b in a {

		}

		for b, c in a {

		}

		for _, c in a {

		}

		for _ in a {

		}

		if (a == 5) {

		} elseif (a == 4) {

		} else {

		}

		switch (a) {
			case 1:
				return true;
				break;
			default:
				return false;
				break;
		}

		return true;
	}

	// See fn is allowed like shortcut
	public fn method2() -> <Test>
	{
		call_user_func(function() { echo "hello"; });


		[1, 2, 3, 4, 5]->walk(
			function(int! x) {
				return x * x;
			}
		);

		[1, 2, 3, 4, 5]->walk(
            function(_, int key) { echo key; }
        );

        array input = [1, 2, 3, 4, 5];

        input->walk(
			function(_, int key) { echo key; }
		);


		input->map(x => x * x);

		return this;
	}

	public function method3() -> int
	{
		var a, image;

		let a = new CustomClass();

		let a = 2 + 1 * 2;

		let a = this->testVar;

		let a = this->testVar + 5;


		let image = new Image();

		// named
		i->chop(width: 100); // width=100, height=400, x=0, y=0
        i->chop(height: 200); // width=600, height=200, x=0, y=0
        i->chop(height: 200, width: 100); // width=100, height=200, x=0, y=0
        i->chop(x: 20, y: 30); // width=600, height=400, x=20, y=30

		return 1;
	}

    public function ord(string! c)
    {
        uchar ch;

        let ch = c[0];

        if ch <= 0x7F {
            return ch;
        }

        if ch < 0xC2 {
            return false;
        }

        if ch <= 0xDF {
            return (ch & 0x1F) << 6  | (c[1] & 0x3F);
        }

        if ch <= 0xEF {
            return (ch & 0x0F) << 12 | (c[1] & 0x3F) << 6  |
                    (c[2] & 0x3F);
        }

        if ch <= 0xF4 {
            return (ch & 0x0F) << 18 | (c[1] & 0x3F) << 12 |
                    (c[2] & 0x3F) << 6 | (c[3] & 0x3F);
        }

        return false;
    }
}
```

**Pull request merged**
