### PR TITLE
New Theme: Agate

### PR DESCRIPTION
**Pull request by tovic**
Add _Agate_ theme by me. Screenshot(s):

### CODE REVIEW

**Comment by Sannis** [comment]
Can you please add it to demo page according to [contributor checklist](http://highlightjs.readthedocs.org/en/latest/style-contribution.html) and add yourself to authors list?

**Comment by tovic** [comment]
Done.

**Comment by isagalaev** [comment]
Hey @tovic! I merged all your pull requests for this theme. For future reference, the best and easiest way to update your pull request is to simply push your new commit into the existing branch that you have requested to pull. No need to create a whole new pull request for each commit. In other words, a pull request represents a complete independent chunk of contribution.

**Comment by tovic** [comment]
Thanks a lot.

Yeah, I was screwed them up in the middle. Sorry.

**Pull request merged**
