### PR TITLE
Update license with up-to-date year

### PR DESCRIPTION
**Pull request by fay-jai**
Only made 1 change:
1) Modified LICENSE to use a year range and included the latest year

No other changes were made.

### CODE REVIEW

**Comment by isagalaev** [comment]
Frankly, I don't see the point. It introduces something new to keep an eye on without any apparent benefit. Come to think of it, I'd rather remove the year altogether...

**Comment by fay-jai** [comment]
Ok no worries - just thought you'd be interested in keeping the year up-to-date.

**Comment by Terri5732** [comment]
Yes I appreciate that thanks.

Terri   Sent from my iPad

**Comment by isagalaev** [comment]
Thanks for chiming in anyway :-)

**Pull request closed without merging**
