### PR TITLE
Add xt256 style

### PR DESCRIPTION
**Pull request by initbar**
[demo](https://initbar.github.io/project/r0tt3nm1lk/playground.html)

### CODE REVIEW

**Comment by Sannis** [comment]
Can you please add yourself to README and Authors files?

**Comment by initbar** [comment]
I wasn't sure about my name in `AUTHORS.ru.txt`

**Comment by isagalaev** [comment]
@initbar adding to just AUTHORS.en is okay, we'll transliterate it for the Russian version.

**Comment by initbar** [comment]
@isagalaev Okay I understand.
@Sannis I've included my name in `AUTHORS*.md` and `CHANGES.md`. Where would I include to the  `README`?

**Comment by isagalaev** [comment]
> Where would I include to the README

I believe @Sannis meant CHANGES.md

**Comment by initbar** [comment]
That's good :) Are my commits acceptable for merge?

**Comment by isagalaev** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
