### PR TITLE
Add a new language: shell-session (also console)

### PR DESCRIPTION
**Pull request by MakeNowJust**
This pull request introduces the highlight called `console` or `sh-session` on GitHub. It is inspired by pygments one and atom language-shellscript:

  - [pygments one](https://bitbucket.org/birkenfeld/pygments-main/src/8455eabb162471c81a92dbe53c0dfdbbf0eca614/pygments/lexers/shell.py#shell.py-179)
  - [atom language-shellscript](https://github.com/atom/language-shellscript/blob/master/grammars/shell-session.cson)

It is really useful to show shell prompts in a document.

Thanks.

### CODE REVIEW

**Comment by joel-porquet** [comment]
I'd love to see this pull request be merged (I'd like to use it in some slides where I have snippets of shell commands that students should type in). Is there something preventing this request from being merged and that I can help with? Thanks.

**Comment by MakeNowJust** [comment]
@joel-porquet Thanks for response. I'm happy to make sure that this language is needed.

One problem: I don't know who maintains this repository, so I couldn't approach to merge it. I will resolve conflicts for now.

**Comment by joel-porquet** [comment]
Hi @MakeNowJust,
For the moment, I hacked the console support into my slides directly. Here is how I modified what you wrote:
```

function() {
    return {
      contains: [
        {
          className: 'section',
          begin: /^[\w\d\[\]()@-\s/~:]*[>%$#]/,
          starts: {
            end: '$', subLanguage: 'bash',
            relevance: 1,
          }
        },
      ]
    }
  }

```

**Comment by isagalaev** [comment]
Merged with a few modification. The language is now called simply "shell". Thanks for the contribution!

**Pull request merged**
