### PR TITLE
Added Android Studio Theme

### PR DESCRIPTION
**Pull request by kanytu**
Android Studio theme for XML and Java added.

### CODE REVIEW

**Comment by Sannis** [comment]
@kanytu, why we cannot use this color scheme for other languages?

**Comment by Terri5732** [comment]
Great thanks guys!!

**Comment by kanytu** [comment]
@Sannis I'm not familiar with other languages so in order to avoid getting a messy css I limited only for java. Although I can spend some time fixing it if it's necessary.

**Comment by Sannis** [comment]
I'll keep this PR open until you or somebody else or one of maintainers will have time to improve it.

Anyway thanks for your PR!

**Comment by isagalaev** [comment]
Language-specific styles are actually an anti-pattern in highlight.js, they're supposed to be universal. So, even a suboptimal highlighting of other languages is better than none.

**Comment by kanytu** [comment]
Theme has been updated and is not language-specific anymore.

**Comment by Sannis** [comment]
Thanks, merged!

**Comment by Sannis** [comment]
I've also add some custom styles for addition/deletion/change selectors.

**Pull request merged**
