### PR TITLE
Enhanced Backus-Naur Form

### PR DESCRIPTION
**Pull request by mckibbenta**
Should highlight basic EBNF as defined by ISO 14977.

### CODE REVIEW

**Comment by mckibbenta** [comment]
Just as with ABNF, rule names are only highlighted at the point where they are declared.

**Comment by mckibbenta** [comment]
Well I don't immediately know why the CI build is failing. I'll look more at that when I get a chance.

Testing using the "highlight.js developer" page works fine as does the mocha test in my environment.

I'd be grateful for any tips as to what might have gone wrong.

**Comment by mckibbenta** [comment]
It seems my unwieldy regular expressions have been the root of all issues I've had in contributing to this project so far!

**Comment by isagalaev** [comment]
Merged! Thanks for your patience!

> unwieldy regular expressions have been the root of all issues

They usually are :-)

**Comment by mckibbenta** [comment]
Awesome =) No worries, glad I could contribute!

**Pull request merged**
